package com.pothole.engine.controller;

import com.pothole.engine.respository.PotholeSummary;
import com.pothole.engine.respository.PotholeSummaryRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/api/pothole_summary/v1") // This means URL's start with /pothole (after Application path)
public class PotholeSummaryController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PotholeSummaryRepository potholeSummaryRepository;

    @GetMapping(path="/all")
    public @ResponseBody Iterable<PotholeSummary> getAllPotholeSummary() {
        // This returns a JSON or XML with the users
        return potholeSummaryRepository.findAll();
    }

    @GetMapping(path="/get")
    public @ResponseBody Iterable<PotholeSummary> getClosestPothole(@RequestParam long userId,
                                                                    @RequestParam double latitude,
                                                                    @RequestParam double longitude,
                                                                    @RequestParam double threshold) {

        // This returns a JSON or XML with the users
        return potholeSummaryRepository.findClosestPothole(latitude, longitude, threshold);
    }
}